version: '2'

services:
    application:
        build: 'docker/code'
        container_name: jt2016_uco_app
        volumes:
            - './simplesamlphp:/var/simplesamlphp'
            - './web:/var/www/symfony'
        tty: true
    php:
        build: 'docker/php7-fpm'
        container_name: jt2016_uco_php
        expose:
            - '9001'
        volumes_from:
            - 'application'
        volumes:
            - 'cache:/var/simplesamlphp/cache'
        links:
            - 'mysql'
        environment:
            - 'SYMFONY_ENV=dev'
    nginx:
        build: 'docker/nginx'
        container_name: jt2016_uco_nginx
        ports:
            - '0.0.0.0:80:80'
        links:
            - 'php'
        volumes_from:
            - 'application'
        volumes:
            - './docker/logs/nginx/:/var/log/nginx'
    mysql:
        image: 'mysql:latest'
        container_name: jt2016_uco_db
        volumes:
            - 'data:/var/lib/mysql'
        environment:
            - 'MYSQL_ROOT_PASSWORD=mysql'

volumes:
    data:
        driver: local
    cache:
        driver: local

